version: '3'

services:
  app:
    image: ktb-travel-spring:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8090:8090"
    environment:
      SPRING_PROFILES_ACTIVE: "prod" # 필요한 경우 스프링 프로필을 설정할 수 있습니다.
    networks:
      - app-network

networks:
  app-network:
    driver: bridge